### ISSUE TITLE
summer rework roadmap

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/pinpoint#164]
want to get this project in a workable state by this summer in a timely manner. will involve some pretty significant reworking. here's a tentative plan, based on my experience toying around with https://github.com/bobheadxi/timelines, which i'll make public after exams and update this ticket with specific examples

## refactoring

- [ ] drop `core`-`gateway` model, drop all protobufs, and condense into a single backend
- [ ] drop REST API, use [graphql](https://graphql.org/). this will save a lot of time both clientside and serverside since there's a lot of codegen tooling around it both for Go and React, and less headache designing APIs
- [ ] drop custom users, leverage something like [AWS Cognito](https://aws.amazon.com/cognito/)
- [ ] drop any redundant code and close all relevant issues

## features

TBD - probably a similar featureset to before, so most of the existing issues still stand

paging @schemetrical, @gbvivian, @suujia, and anyone else interested

**Comment by srijonsaha** [comment]
> drop core-gateway model, drop all protobufs, and condense into a single backend

😮 basically rewrite the entire project

**Comment by bobheadxi** [comment]
not entirely - just remove some of the boilerplate in between. I don't expect much change in `core` (DB wrappers, etc) - it'll just be functions called directly, instead of procedure calls. The only exception is probably the user code

on the `gateway` side... there really isn't all that much stuff there 😋

**Comment by suujia** [comment]
When robs coding skills are growing at an exponential rate while this project is growing linearly

**Comment by bobheadxi** [comment]
made my repo public, some examples:

* graphql
   * [bad schema](https://github.com/bobheadxi/timelines/blob/master/graphql/schema.graphql)
   * [what using the generated code looks like](https://github.com/bobheadxi/timelines/blob/master/server/query.go)
   * [playground](https://timelines-api.herokuapp.com/playground), [sourcegraph playground](https://sourcegraph.com/api/console)
   * [on the frontend](https://github.com/bobheadxi/timelines/tree/master/web#graphql-queries) ([usage](https://github.com/bobheadxi/timelines/blob/master/web/src/pages/Owner/Owner.tsx#L30))

**Comment by bobheadxi** [comment]
https://docs.google.com/document/d/1EW2qNKCYPfZb8CCtHPHSntMyUOJomHNWxbLJ1bkSPj8/edit#
